version: '3.4'

services:
  analytics:
    runtime: nvidia
    shm_size: 4g
    env_file:
      - env.list
    image: analytics:v2
    container_name: analytics
    network_mode: "host"    
    volumes:
      - "./code:/code"
      - ${WEED_DATA_PATH}:/weed_data
      - "./model:/model"
    entrypoint: ["python3", "/code/app.py"]
    