name: myenv
channels:
  - defaults
  - conda-forge    
  #- pytorch
  #- cannylab
dependencies:
  - python=3.8
  - pip  
  #- cudatoolkit=11.1
  #- cudatoolkit
  #- pytorch=1.8.0
  #- pytorch
  #- cudatoolkit=11.0
  #- pytorch==1.7.1 
  #- torchvision==0.8.2
  #- torchvision=0.9.0  
  #- torchvision
  #- tsnecuda
  - pip:
    #- torch==1.8.0+cu111 torchvision==0.9.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
    #- torch==1.7.1+cu110 -f https://download.pytorch.org/whl/torch_stable.html
    #- torchvision==0.8.0+cu110 -f https://download.pytorch.org/whl/torch_stable.html
    - setuptools
    - requests
    - pillow
    - matplotlib
    - flask
    - pymongo
    - pandas
    - numpy
    - dash
    #- pytorch==1.6.0+cu101
    #- torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html  
    #- torchvision==0.7.0+cu101
    #- tsnecuda -c cannylab  
    
 